---
#
# Tasks and roles for all hosts
#
- hosts: space
  gather_facts: no

- hosts: space
  become: yes
  roles:
    - role: system
      tags: 
        - system

    - role: samdoran.fish
      become: yes
      tags: 
        - fish
        
    - role: docker
      tags: 
        - docker
  
    - role: artis3n.tailscale
      tags: 
        - tailscale

    - role: user
      tags: 
        - user

    - role: fubarhouse.golang
      tags:
        - golang

    - role: sprat.mergerfs
      tags: 
        - mergerfs
        
      # vars:
      #   mergerfs_mounts:
      #     - path: /mnt/data
      #       branches:
      #         - /mnt/data1
      #         - /mnt/data2
      #       options: allow_other,use_ino

    # - role: rclone 
    #   tags: 
    #     - rclone