---
- name: Ensure group "{{ username }}" exists
  become: yes
  group:
    name: "{{ username }}"
    state: present

- name: Create a login user
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: "{{ shell }}"
    groups:
      - thomas
      - sudo
    state: present

- name: Install omf
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes
  become_user: "{{ username }}"

- name: Installing omf for fish user
  command: /tmp/omf/bin/install -y --offline --noninteractive
  become_user: "{{ username }}"

- name: Configure fish
  template:
    src: config.fish.j2
    dest: '/home/{{ username }}/.config/fish/config.fish'
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644