---
- name: Include OS-specific variables
  include_vars: "all.yml"

- name: Install list of packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  with_items: "{{ system_deps }}"

- name: Configure fuse for non root user
  template:
    src: fuse.conf.j2
    dest: '/etc/fuse.conf'
    owner: "root"
    group: "root"
    mode: 644