---
#
# Tasks and roles for all hosts
#
- hosts: space
  gather_facts: no

- hosts: space
  become: yes
  roles:
    - role: system
      tags: 
        - system

    - role: samdoran.fish
      become: yes
      tags: 
        - fish
        
    - role: docker
      tags: 
        - docker

    - role: disks
      tags: 
        - disks

    - role: user
      tags: 
        - user

    - role: fubarhouse.golang
      tags:
        - golang